"use strict"; // treat all js code as new version

//alert(3+3); //we are using node js It will throw error bocz in browser there is a built in javascipt engine but here we have tp use new version javascript syntax
console.log(9+9)// code readability should be higher
console.log("rekha")

let name="rekha" //string
let age=21 //number
let isMarried=false; //boolean

// number - 2 to power of 53
// big int - we will not use this much
// string - " "
// boolean - true/false
//null - standalone value (its empty) - special datatype
// undefined
//symbol


//object
console.log(typeof false)
console.log(typeof null) // NULL'S DATATYPE IS OBJECT
console.log(typeof undefined) //undefined's datatype is undefined only